### ISSUE TITLE
head-room margin per SAS is not accounted for in the calculation in calculatePostIapAggregateInterference

### ISSUE THREAD

**Issue by jni2000** [Wireless-Innovation-Forum/Spectrum-Access-System#651] opened 2018-05-16 13:28 UTC
> Navin
with regards to IAP reference model, when computing the allowed reference aggregate in calculatePostIapAggregateInterference(), the head-room margin per SAS is not accounted for in the calculation.

> Kate: I agree, it seems that the headroom is not being added back in. The current equation in line 643 adds the leftover and the aggregate interference caused by CBSDs managed by SAS UUT, but it omits the difference between `q_p` and the original threshold (i.e. the headroom). I guess we need to add another arg to "calculatePostIapAggregateInterference()" to denote the original threshold, and then this value can be used on line 643. If you agree, can you please submit the fix?

>jni2000
We have thoroughly reviewed the codes and agreed that we need to put in a fix.

**Comment by kate-harrison** [comment] 2018-05-16 16:50
Closing as a duplicate of #637.

**Closed by kate-harrison** 2018-05-16 16:50 UTC
