### ISSUE TITLE
Wrong parameter when calling iapPointConstraint

### ISSUE THREAD

**Issue by redtechnologies** [Wireless-Innovation-Forum/Spectrum-Access-System#647] opened 2018-05-15 12:18 UTC
In performIapForFssCochannel, when the FSS high frequency is below 3700 MHz, the function iapPointConstraint (Line 532) should include the parameter "fss_high_freq" instead of the parameter "interf.CBRS_HIGH_FREQ_HZ.".

Possible update:

if fss_high_freq < interf.CBRS_HIGH_FREQ_HZ:
  iapPointConstraint(protection_point, protection_channels, fss_low_freq,
    **fss_high_freq**, grant_objects, fss_info, None, 
    None, fss_cochannel_iap_threshold, 
    data.ProtectedEntityType.FSS_CO_CHANNEL,
    asas_interference, aggregate_interference) 
else 
 iapPointConstraint(protection_point, protection_channels, fss_low_freq,
    **interf.CBRS_HIGH_FREQ_HZ**, grant_objects, fss_info, None, 
    None, fss_cochannel_iap_threshold, 
    data.ProtectedEntityType.FSS_CO_CHANNEL,
    asas_interference, aggregate_interference)

**Comment by kate-harrison** [comment] 2018-05-16 20:21
Sections 8.8.3.4 and 8.8.3.4.2 of the test spec confirm that the current code is incorrect. I think your fix is correct, but this should also work (and will avoid two very similar pieces of code which may inadvertently diverge in the future):

```
iapPointConstraint(protection_point, protection_channels, fss_low_freq,
  min(fss_high_freq, interf.CBRS_HIGH_FREQ_HZ), grant_objects, fss_info, None,
  None, fss_cochannel_iap_threshold,
  data.ProtectedEntityType.FSS_CO_CHANNEL,
  asas_interference, aggregate_interference)
```

Can you please make a PR?

**Comment by nasrinivasa** [comment] 2018-05-16 21:19
Section 8.8.3.3 seems to be defining 2 FSS types, are they representative of the FSS types that will be used for testing? Here the upper edge of the FSS types are fixed at 4200 MHz, which makes the FSS co-channel part to be fixed at 3700MHz (FSS Scenario 1). 
Also if the FSS upper frequency is < 3700 MHz, then what is the filter mask for the portion between FSS upper edge to 3700?

**Comment by kate-harrison** [comment] 2018-05-16 21:30
You're right, Navin. Yi from Google confirmed that the upper freq for the FSS passband will always be >= 3700. So I guess my code is technically correct but the `min()` will always evaluate to 3700 MHz based on this constraint, so actually there doesn't seem to be a problem in the existing code (which hard codes 3700 MHz).

Reda (? I don't remember who uses this GitHub username?), if you agree with our analysis, please close the issue. Otherwise, please let us know what we've missed :)

**Comment by credtech** [comment] 2018-05-17 08:55
Ok perfect thanks for your feedback; if FSS high frequency is always above 3700, it should be fine.

Just in case,  it may be safer to delete the following lines 525 to 527 (since it is not supposed to happen and would cause issues during IAP procedure in case some grants are entirely above fss_high_freq):

  if fss_high_freq < interf.CBRS_HIGH_FREQ_HZ:
    protection_channels = interf.getProtectedChannels(fss_low_freq, fss_high_freq)
  else:

**Comment by kate-harrison** [comment] 2018-05-18 16:01
Yeah, I think it would make sense to assert that `fss_high_freq >= interf.CBRS_HIGH_FREQ_HZ` somewhere near the beginning to detect config errors. Then we can very safely take out the lines you mentioned. Can you please create a PR for this?

**Comment by sbdt-google** [comment] 2018-05-22 13:31
Closing since done.
One PR will change use of assert to proper raising, so the test is not hidden.

**Closed by sbdt-google** 2018-05-22 13:31 UTC
