### ISSUE TITLE
CBSD Operation state to be changed to AUTHORIZED in subsequent HBT request for CBSDs with previously approved heartbeat

### ISSUE THREAD

**Issue by chandanahs** [Wireless-Innovation-Forum/Spectrum-Access-System#797] opened 2018-08-09 19:52 UTC
Function "executeSingleMCPIteration" from Spectrum-Access-System/src/harness/testcases/WINNF_FT_S_MCP_testcase.py is used to execute FPR_1-4 testcases STEPS.

    self.executeMcpTestSteps(config, 'xPR2')

In steps 13-16, first heartbeat request for all grants are sent and CBSDs moved to AUTHORIZED. As part of steps 20 and 23, Heartbeat requests for all the grants are executed with OperationState of the CBSD as “GRANTED” without considering if the previous Heartbeat requests are successful, moving CBSD to AUTHORIZED.

    # Steps 13, 14, 15, and 16: send heartbeat request for the grants,
    # relinquish the grant, grant request and heartbeat for new grants.
    logging.info('Steps 13 - 16: heartbeat, relinquish, grant, heartbeat.')
    for index, domain_proxy_object in enumerate(self.domain_proxy_objects):
      logging.info('Working on domain proxy %d.', index)
      domain_proxy_object.performHeartbeatAndUpdateGrants()

    # Step 20: Send heartbeat request for all CBSDs managed by SAS UUT.
    logging.info('Step 20: heartbeating all CBSDs.')
    for index, domain_proxy_object in enumerate(self.domain_proxy_objects):
      logging.info('Heartbeating for domain proxy %d.', index)
      domain_proxy_object.heartbeatForAllActiveGrants()

    # Step 23: Send heartbeat request for all CBSDs managed by SAS UUT.
    logging.info('Step 23: heartbeating all CBSDs.')
    for index, domain_proxy_object in enumerate(self.domain_proxy_objects):
      logging.info('Heartbeating for domain proxy %d.', index)
      domain_proxy_object.heartbeatForAllActiveGrants()

  def heartbeatForAllActiveGrants(self):
    # Concatenate all the heartbeat request of CBSD into single request.
    heartbeat_requests = []
    heartbeat_responses = []
    for cbsd_object_item in self.cbsd_objects.itervalues():
      heartbeat_requests.extend(cbsd_object_item.constructHeartbeatRequestForAllActiveGrants())

  def constructHeartbeatRequest(self):
    """Constructs heartbeat request for the grant object."""
    heartbeat_request = {
        'grantId': self.grant_id,
        'cbsdId': self.grant_request['cbsdId'],
        'operationState': 'GRANTED'
      }
    return heartbeat_request

CBSD Operation state is not modified from GRANTED to AUTHORIZED in subsequent HBT requests(Steps 20 & 23) when CBSD state is AUTHORIZED  and hence HBT request is failing with “502: UNSYNC_OP_PARAM”.

"502:UNSYNC_OP_PARAM” is not considered as one of the possible expected response code either.
  def heartbeatForAllActiveGrants(self):
        self._mapResponseCodeToGrantState(heartbeat_response['response']['responseCode'], grant_object)
 def _mapResponseCodeToGrantState(self, heartbeat_response_code, grant_object):
    """Maps the heartbeat response and update the grant state."""
    if heartbeat_response_code == ResponseCodes.SUCCESS.value:
      grant_object.authorized_in_last_heartbeat = True
    elif heartbeat_response_code == ResponseCodes.TERMINATED_GRANT.value:
      grant_object.is_terminated = True
      grant_object.authorized_in_last_heartbeat = False
    elif heartbeat_response_code == ResponseCodes.SUSPENDED_GRANT.value:
      grant_object.authorized_in_last_heartbeat = False
    else:
      logging.error('Unknown code=%s received in Heartbeat Response',heartbeat_response_code)
      raise Exception('Unknown code received in Heartbeat Response')

**Comment by kate-harrison** [comment] 2018-08-09 20:03
I don't recognize your username; may I ask your name and affiliation?

The test code was designed in this way to reduce overall complexity. Tracking the Grant's operationState would require carefully tracking the transmitExpireTime of each HB response, not just the last heartbeat's responseCode. This would significantly increase the complexity of the code and the potential for errors.

Furthermore, I believe that it only makes sense for a SAS to respond with UNSYNC_OP_PARAM in the case where the CBSD believes it has more permissions than it actually does (i.e. the opposite of the situation you're describing, where the CBSD says AUTHORIZED but it is only GRANTED). There are many reasons, including a lost heartbeat response, which may cause the CBSD to believe it is only GRANTED when in fact is it AUTHORIZED -- and only the reverse is actually a problem for Part 96 compliance. I'd suggest that it be the common practice of SASes to only send UNSYNC_OP_PARAM in the case where the state discrepancy may lead to Part 96 violations.

Please let me know your thoughts on this.

**Comment by chandanahs** [comment] 2018-08-09 20:32
Thanks Kate for the immediate response.

I'm Chandana From Nokia.

Yes, we do agree with you. 

We implemented based on this requirement "502:UNSYNC_OP_PARAM:Operation parameters or Grant state(s) is/are out of sync between the CBSD and the SAS. In this case, the CBSD shall immediately turn off all radio transmission and shall relinquish the Grant."

we also looked in to "SAS Providers Agreements" for 502 response code, Will it be added to have synchronized SASes all across?

**Comment by kate-harrison** [comment] 2018-08-09 20:39
Great! In that case, are you OK to resolve this issue since there is no problem in the test harness?

I'm not quite sure what you mean with your last paragraph. If you can explain a bit more, I'll be happy to answer.

**Comment by chandanahs** [comment] 2018-08-09 20:56
Yes, We can fix it from SAS side.

We had received "SAS Provider WG Agreements_5-15-V0.41.docx" with list of agreements to have all the SAS's admins with the same understanding, So could this agreement be added to the above document.

Is this the same understanding with all the SASs admins?

**Comment by kate-harrison** [comment] 2018-08-09 21:04
I'm not sure if this is included in that document or not. I expect that all SAS Admins have the same understanding since we discussed this particular decision in one of our test code development meetings. If you would like to add it to the document, please send a proposal to the SAS Admins mailing list. I'll close this issue now since there's no work to be done on the test harness.

**Closed by kate-harrison** 2018-08-09 21:04 UTC
